{% set name = "msgspec" %}
{% set version = "0.20.0" %}

package:
  name: {{ name|lower }}-suite
  version: {{ version }}

source:
  # Use GH to include upstream tests
  url: https://github.com/jcrist/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: fd1f5aa07501516720bfaa3f7cbcb7170a0b944d3f49ee107caf0fa56d056d9c

build:
  number: 0
  skip: true  # [py<39]
requirements:
  host:
    - python

outputs:
  - name: {{ name }}
    version: {{ version }}
    script: build_msgspec.bat  # [win]
    script: build_msgspec.sh   # [not win]
    requirements:
      build:
        - {{ stdlib('c') }}
        - {{ compiler('c') }}
      host:
        - python
        - pip
        - setuptools
        - wheel
      run:
        - python

    {% set ignore_tests_files = "" %}
    # ERROR tests/prof/perf - ModuleNotFoundError: No module named 'benchmarks'
    {% set ignore_tests_files = ignore_tests_files + " --ignore=tests/prof" %}
    {% set ignore_tests_files = ignore_tests_files + " --ignore=tests/typing/test_pyright.py" %}

    test:
      imports:
        - msgspec
      requires:
        - pip
        - pytest
        - mypy
        - attrs
        - pyyaml
        - tomli    # [py<311]
        - tomli-w
        - msgpack-python
      source_files:
        - tests
        - src/msgspec/_core.c
        - pyproject.toml
      commands:
        - pip check
        - pytest -ra -v {{ ignore_tests_files }} tests

  - name: {{ name }}-yaml
    version: {{ version }}
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage(name) }}
        - pyyaml
    test:
      imports:
        - msgspec
      requires:
        - pip
        - pytest
        - mypy
        - attrs
        - pyyaml
        - tomli    # [py<311]
        - tomli-w
        - msgpack-python
      source_files:
        - tests
        - src/msgspec/_core.c
        - pyproject.toml
      commands:
        - pip check
        - pytest -ra -v {{ ignore_tests_files }} tests

  - name: {{ name }}-toml
    version: {{ version }}
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage(name) }}
        - tomli    # [py<311]
        - tomli-w
    test:
      imports:
        - msgspec
      requires:
        - pip
        - pytest
        - mypy
        - attrs
        - pyyaml
        - tomli    # [py<311]
        - tomli-w
        - msgpack-python
      source_files:
        - tests
        - src/msgspec/_core.c
        - pyproject.toml
      commands:
        - pip check
        - pytest -ra -v {{ ignore_tests_files }} tests

about:
  home: https://jcristharif.com/msgspec
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: |
    A fast serialization and validation library, with builtin support for JSON,
    MessagePack, YAML, and TOML.
  description: |
    `msgspec` is a fast serialization and validation library for Python,
    supporting JSON, MessagePack, YAML, and TOML. It integrates well with
    Python's type annotations, providing ergonomic (and performant!) schema
    validation.
  doc_url: https://jcristharif.com/msgspec
  dev_url: https://github.com/jcrist/msgspec

extra:
  recipe-maintainers:
    - jcrist
