{% set name = "msgspec" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8258ff99995dd542bc8fb49d35a58a19752ce6b7ba7bd1e2de0df55e5e3d3e97

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - msgspec

about:
  home: https://jcristharif.com/msgspec/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A fast and friendly MessagePack implementation for Python
  description: |
    `msgspec` is a fast and friendly implementation of the MessagePack protocol
    for Python 3.8+. In addition to serialization/deserialization, it supports
    runtime message validation using schemas defined via Python's type
    annotations.
  doc_url: https://jcristharif.com/msgspec/
  dev_url: https://github.com/jcrist/msgspec

extra:
  recipe-maintainers:
    - jcrist
