{% set name = "msgspec" %}
{% set version = "0.18.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # Use GH to include upstream tests
  url: https://github.com/jcrist/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 5bff8c3f9303eb589516e02de4141ce31be09a0fdf4980734b020b64c120295e

build:
  number: 0
requirements:
  host:
    - python

outputs:
  - name: {{ name }}
    version: {{ version }}
    build:
      # Skip s390x as it's optional and fails some tests
      skip: true  # [py<38 or s390x]
      script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
    requirements:
      build:
        - {{ compiler('c') }}
      host:
        - python
        - pip
        - setuptools
        - wheel
      run:
        - python
    test:
      imports:
        - msgspec
      requires:
        - pip
        - pytest
      source_files:
        - tests
        - msgspec/_core.c
        - setup.cfg
      commands:
        - pip check
        - pytest tests

  - name: msgspec-yaml
    version: {{ version }}
    requirements:
      host:
        - python
      run:
        - {{ pin_subpackage(name) }}
        - pyyaml
    test:
      imports:
        - msgspec
      requires:
        - pip
        - pytest
      source_files:
        - tests
        - msgspec/_core.c
        - setup.cfg
      commands:
        - pip check
        - pytest tests

  - name: msgspec-toml
    version: {{ version }}
    requirements:
      host:
        - python
      run:
        - {{ pin_subpackage(name) }}
        - tomli    # [py<311]
        - tomli-w
    test:
      imports:
        - msgspec
      requires:
        - pip
        - pytest
      source_files:
        - tests
        - msgspec/_core.c
        - setup.cfg
      commands:
        - pip check
        - pytest tests


about:
  home: https://jcristharif.com/msgspec/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: |
    A fast serialization and validation library, with builtin support for JSON,
    MessagePack, YAML, and TOML.
  description: |
    `msgspec` is a fast serialization and validation library for Python,
    supporting JSON, MessagePack, YAML, and TOML. It integrates well with
    Python's type annotations, providing ergonomic (and performant!) schema
    validation.
  doc_url: https://jcristharif.com/msgspec/
  dev_url: https://github.com/jcrist/msgspec

extra:
  recipe-maintainers:
    - jcrist
